"""baseline schema (records + role tables)

Revision ID: efcbb17ae78b
Revises:
Create Date: 2026-09-19 08:10:49.967447

This is an intentionally empty baseline. db_sql.py still calls
Base.metadata.create_all()/ModelsBase.metadata.create_all() on import (that
behavior is unchanged), so on an already-running database the tables this
migration would create already exist.

How to adopt Alembic on an existing (already create_all'd) database:
    alembic stamp head

How to adopt it on a brand-new, empty database instead of relying on
create_all: run `alembic upgrade head` before starting the app once, and
then remove/no-op the create_all() calls in db_sql.py so Alembic becomes
the single source of truth for schema. (Left as a deliberate choice for
you to make, rather than changed here, since it affects every deployment.)

From here on, any change to models.py or db_sql.py's Record table should
get its own migration:
    alembic revision --autogenerate -m "describe the change"
    alembic upgrade head
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcbb17ae78b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
